// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-ITLeTM09D7PkyU1GJqlHrlnSDCZ8nLc',
    appId: '1:1011968249422:web:a790ec16b4443b8c37bd1f',
    messagingSenderId: '1011968249422',
    projectId: 'bus-bee-ce6fa',
    authDomain: 'bus-bee-ce6fa.firebaseapp.com',
    storageBucket: 'bus-bee-ce6fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR7AK4SKTLZFWxLfVda1Zp2-BSrCZnm2M',
    appId: '1:1011968249422:android:b1aec99b485f63d437bd1f',
    messagingSenderId: '1011968249422',
    projectId: 'bus-bee-ce6fa',
    storageBucket: 'bus-bee-ce6fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv-UNn0V8FQAesga3445w34RMbhv1hIvY',
    appId: '1:1011968249422:ios:4a39b1eee21799c937bd1f',
    messagingSenderId: '1011968249422',
    projectId: 'bus-bee-ce6fa',
    storageBucket: 'bus-bee-ce6fa.firebasestorage.app',
    iosClientId: '1011968249422-3qp4rccf21fvohoelm9788gug5902v3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv-UNn0V8FQAesga3445w34RMbhv1hIvY',
    appId: '1:1011968249422:ios:4a39b1eee21799c937bd1f',
    messagingSenderId: '1011968249422',
    projectId: 'bus-bee-ce6fa',
    storageBucket: 'bus-bee-ce6fa.firebasestorage.app',
    iosClientId: '1011968249422-3qp4rccf21fvohoelm9788gug5902v3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-ITLeTM09D7PkyU1GJqlHrlnSDCZ8nLc',
    appId: '1:1011968249422:web:c710e44a6110dfe037bd1f',
    messagingSenderId: '1011968249422',
    projectId: 'bus-bee-ce6fa',
    authDomain: 'bus-bee-ce6fa.firebaseapp.com',
    storageBucket: 'bus-bee-ce6fa.firebasestorage.app',
  );

}